name: Build Docker Image

on: 
  push:
    branches: 
      - "main"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'docker/**'
      - 'Dockerfile'
      - '.dockerignore'
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  COMMIT_SHA: ${{github.sha}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Log in to the Container registry
      uses: docker/login-action@v3.2.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}


    - name: Build and push Docker image
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        push: ${{ contains(fromJSON('["push", "release"]'), github.event_name) }}
        tags: ${{ steps.meta.outputs.tags }}
        build-args: |
          BUILD_COMMIT=$COMMIT_SHA
          BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')